### ISSUE TITLE
Feature Request: Zoom on an image?

### ISSUE THREAD

**Issue by zx8754** [christophergandrud/networkD3#105]
Something like this:

http://codepen.io/billdwhite/pen/lCAdi
http://www.billdwhite.com/wordpress/2013/11/26/d3-minimap-pan-and-zoom-demo/

When we have large network diagrams, it is better to save as image, then open as image for exploration?

**Comment by cjyetman** [comment]
Zooming is possible on the network plots, but on an image? Currently there is no possibility of displaying an image along with one of the available network plots. Can you explain this better?

**Comment by zx8754** [comment]
@cjyetman It has been a long time since requested, as far as I remember, when zooming on "live" diagram there is a lag when the diagram is huge? So, if there was an option of outputting the plot as an image with no interactivity apart from zooming using linked posts?

Let me know if it is still not clear, will try to dig out more info.

**Comment by cjyetman** [comment]
a few thoughts (assuming you're talking about force network plots)...
1. the recently released version 0.3 on CRAN was upgraded to use D3 v4+, which supposedly has substantial performance gains when rendering force networks, so you should give it a try if you haven't recently (after updating networkD3 obviously)
2. we are currently considering adding the ability to plot using canvas rather than svg (#161), which might add additional performance gains. If you have specific, real-world examples of force network plots that are slow because of a lot of data that you could share with us, that would be great
3. if you're using RStudio and the force network plot is showing in the 'Viewer' window, try clicking the "Show in new window" button which should open it in your default browser, which I have found to be significantly faster than RStudio's built-in browser. I think that if you're not using RStudio, it will open in a browser window already.
4. if you're viewing the force network plot in RStudio's viewer you can certainly export an image of it and view it in whatever image viewer you prefer
5. I have considered an option of producing a static force network plot in which node and link positions would be calculated once in the beginning and then the nodes and links would remain stationary, but still be interactive. I think that would solve the performance issues (though large networks would still take significant time for the initial position calculation) without losing the nice interactive features. Keep an eye out for that if you're interested.

Otherwise, can we close this ticket since there seem to be adequate solutions to this problem already?

**Comment by zx8754** [comment]
Yes, it was force network plots, within Shiny app.

I will have to run some tests if it improves with the new release. We can close this issue, thank you.
