### ISSUE TITLE
forceNetwork node label/text font color 

### ISSUE THREAD

**Issue by rickyars** [christophergandrud/networkD3#123]
It's really hard to read the node label/text since it's the same color as the nodes when using forceNetwork layout. It would be nice if we could specify the text color independently from the node color. E.g, I've noticed an option in simpleNetwork called textColour. It would also be nice if the text were on top of (instead of behind) the nodes.

**Comment by christophergandrud** [comment]
I'ld be happy to consider a pull request.

**Comment by cjyetman** [comment]
it also might make sense, or even more sense, to use a thin white outline around the text to make it stand out (for example: [Bostock's Oscar viz](http://www.nytimes.com/interactive/2013/02/20/movies/among-the-oscar-contenders-a-host-of-connections.html))

This can be achieved either by setting e.g. `stroke-width: .5px; stroke: #fff;` on the text element, or even better putting another text element just above the existing one with e.g. `stroke-width: 2px; stroke: #fff;`. In the second version, the `stroke-width` can be bigger because it will only be seen outside of the font border, not inside the font border, which is preferable. (This could also be achieved with [`paint-order="stroke"`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/paint-order), but it is sadly not supported by IE).
