### ISSUE TITLE
Creating SankeyNetwork with multiple layers

### ISSUE THREAD

**Issue by mcharles** [christophergandrud/networkD3#134]
I'm having difficulty creating a SankeyNetwork that has 3 layers of nodes. I'm able to execute the Energy Sources example that comes with the package correctly, and I've scrutinized differences between those links/nodes dataframes and my own - but can't find my mistake. 

I have a reproducible example at the following gist:
https://gist.github.com/mcharles/8f7e5ee20f051ab226ce5cd468880b6b

I'm not sure if this question is appropriate for 'Issues' @ GitHub because I'm fairly certain this isn't a bug, but some silly mistake that I keep overlooking. Sorry if this should be asked elsewhere (didn't get a response on SO, a bit time crunched)

**Comment by ivot** [comment]
Hi mcharles,

If you check your nodes data.frame you see that ID's are not sequential (they skip 2 IDs, because you take unique records). If you add one line into your function, which renumbers all rows in your nodes data.frame, then plotting works.

Ivan


sanktify <- function(x) {
  
  # Create nodes DF with the unique sources & targets from input
  nodes <- unique(data.frame(c(unique(x$source), unique(x$target))))

  # Renumber all rows to have sequential IDs for sankeyNetwork to work properly
  **row.names(nodes)<-1:nrow(nodes)**
  
  nodes$ID <- as.numeric(rownames(nodes)) - 1 # sankeyNetwork requires IDs to be zero-indexed
  names(nodes) <- c("name", "ID")
  
  # Create two versions of nodes for merging
  nodes_source <- nodes
  nodes_target <- nodes
  
  names(nodes_source) <- c("source", "source_ID")
  names(nodes_target) <- c("target", "target_ID")
  
  # Replace source & target in links DF with IDs
  links <- merge(x, nodes_source, by="source", all.x=TRUE) %>%
    merge(nodes_target, by="target", all.x=TRUE) %>%
    select(source_ID, target_ID, value) %>%
    arrange(source_ID)
  
  # Create Sankey Plot
  sank <- sankeyNetwork(
    Links = links,
    Nodes = nodes,
    Source = "source_ID",
    Target = "target_ID",
    Value = "value",
    NodeID = "name",
    units = "USD",
    fontSize = 12,
    nodeWidth = 30
  )
  
  return(sank)
  
}

**Comment by mcharles** [comment]
Thank you. The other "fix" was that I was able to switch the order of the
dataframes in rbind() and the plot was produced. But I didn't understand
why.

I knew the importance of sequential indexing from poring over the package
documentation, but I completely forgot that the 'unique' call was altering
the sequence of row.names I was calling for my ID. Thank you! this was
driving me crazy

**Comment by timelyportfolio** [comment]
Forgot to tell you that I commented on the Gist with another solution this weekend.  I'll close this out.  Feel free to reopen.
