### ISSUE TITLE
networkD3 not working with rCharts and NVD3 in Shiny

### ISSUE THREAD

**Issue by simdadim** [christophergandrud/networkD3#150]
Hi

First of all, thanks for this great package.

To the case - it seems that using both networkD3 and rCharts togheter in the same shiny app doesn't work well. Specifically - if i create a plot with rCharts using NVD3, and then try to create a sankey chart using networkD3, I get the following error in the console: 
`sankeyNetwork.js:14Uncaught TypeError: d3.sankey is not a function`

It seems that some of the required .js files (the one createing the d3.sankey function) are not loaded when rCharts with NVD3 are used as well.

**Comment by timelyportfolio** [comment]
`rCharts` preceded `htmlwidgets`, and one of the most common issues was dependency management.  Instead of not being loaded, I think what actually is occurring is duplicate instances of `d3` supplied by `rCharts` and `htmlwidgets` causing a conflict and the buggy behavior.  We intended to re-implement `rCharts` as `htmlwidgets` to get the benefit of dependency management, but beyond `dimple` that has not happened.

There is not an easy solution other than to manually specify the `nvd3` js and css dependencies, and use `chartOutput` with the argment `add_lib=FALSE`.  See [lines](https://github.com/ramnathv/rCharts/blob/master/R/showOutput.R#L10-L11).
