### ISSUE TITLE
Edges become invisible when setting arrows = TRUE in simpleNetwork/forceNetwork 

### ISSUE THREAD

**Issue by kelvinyangli** [christophergandrud/networkD3#189]
Hi, 

As stated in title, whenever I set arrows to TRUE, edges become invisible in Shiny app. I tested this with the example source code provided.

**Comment by cjyetman** [comment]
The `arrows` argument is not available with the `simpleNetwork` function, so that should not work.

Can you tell us exactly which 'example source code' you're talking about, or paste it here? I tested all of the examples in the help file for `forceNetwork` adding the `arrows = T` parameter and they all worked (with v0.4).

**Comment by kelvinyangli** [comment]
I tested it just now on my macbook, this time it works. There maybe an IE problem with my work computer. I'll test it again next week. Thanks for your reply.
