### ISSUE TITLE
Extra node in shiny forceNetwork

### ISSUE THREAD

**Issue by sirallen** [christophergandrud/networkD3#193]
I made a shiny app that integrates forceNetworks, and there's always an extraneous isolated node that appears along with an extra legend box. I'm not sure what the reason is; it doesn't happen in the RStudio plot window.

![image](https://cloud.githubusercontent.com/assets/6941686/25795468/6f63c034-33a3-11e7-95eb-a2e3cee54e5e.png)

**Comment by christophergandrud** [comment]
There must be something about your shiny app that creates an unnamed node. It's hard to determine this definitively from the outside however.

**Comment by cjyetman** [comment]
is it possible your data has a node that is not linked to any other node?

**Comment by sirallen** [comment]
OK, so it looks like it's caused by interference with another D3 script in my application; I tried commenting things out by trial/error and determined that defining the method
```
Array.prototype.move = function (from, to) {
  this.splice(to, 0, this.splice(from, 1)[0]);
};
```
is the culprit. I can't figure out how this is related to the problem above, though.

**Comment by cjyetman** [comment]
We can't really help you if we can't see all of your code. Additionally, this issue tracking system is primarily meant for submitting bugs and/or feature requests. Unless you have a strong suspicion that the problem you're having is due to a bug in networkD3, then this type of issue is probably better served on stackoverflow (use the networkD3 tag). It will also help a lot if you make a [minimal reproducible example](http://adv-r.had.co.nz/Reproducibility.html).
