### ISSUE TITLE
charts in blogspot?

### ISSUE THREAD

**Issue by merira** [christophergandrud/networkD3#194]
Hey there, 

It might be something really straightforward, but: I have printed a wonderful sankey diagram thanks to your package using markdown. Now, I would like to publish it on a blog (blogger), but somehow all code that I tried does not work. I have come across a couple of issues regarding the publication of R charts, but I cannot seem to find a solution for this. any ideas?

**Comment by cjyetman** [comment]
You will have to be much more specific for anyone to help you, ideally providing a [minimal reproducible example](http://adv-r.had.co.nz/Reproducibility.html). Additionally, unless you believe that the problem you're seeing is likely to be caused by a bug in networkD3, then this type of issue is probably better served on stackoverflow (use the networkD3 tag).

**Comment by christophergandrud** [comment]
Quick background: unfortunately networkD3 has never worked with blogger, I think because of the way blogger handles the JavaScript.

**Comment by merira** [comment]
cheers. that answers it. best,

**Comment by merira** [comment]
in fact, after some back and forth, I managed to include the chart thanks
to iframe.

thanks.
