### ISSUE TITLE
hierarchical forceNetwork()s

### ISSUE THREAD

**Issue by wlandau** [christophergandrud/networkD3#241]
Please forgive my naive question, but is it possible to arrange directed `forceNetwork()` DAGs such that all the edges point from left to right? I am looking for something like the Sugiyama layout for `igraph`s.

**Comment by cjyetman** [comment]
Not sure exactly what you mean, but... `networkD3` and `forceNetwork()` typically attempt to produce "ideal" layouts automatically, so predetermining things like direction of edges (physical direction in the plot, not direction of link between nodes) goes against its purpose.

**Comment by wlandau** [comment]
In that case, what is currently available besides `sankeyNetwork()`? Direction is important for visualizing the chronological execution order of [`drake`](https://github.com/ropensci/drake) [dependency graphs](https://ropenscilabs.github.io/drake-manual/vis.html), which are always DAGs, but not always trees.

**Comment by cjyetman** [comment]
`forceNetwork()` can display arrows for the direction of each link/edge with the `arrows = TRUE` parameter, but you cannot predetermine the x/y location of each node because that works against the primary purpose of the `forceNetwork()` function (to use a psuedo-physics simulation to determine the x/y location of nodes based on attraction, repulsion, link strength, etc.)

At the moment, I don't think `networkD3` has a function that precisely serves your purpose.

**Comment by wlandau** [comment]
Useful to know, I will keep a lookout. If hierarchical DAG layouts do become possible at some point, I will be able to completely switch over from `visNetwork` to `networkD3`.
