### ISSUE TITLE
Example : sankeyNetword/getURL fails under Windows

### ISSUE THREAD

**Issue by dmenne** [christophergandrud/networkD3#284]
windows 10, problem with RCurls and TLS

```
URL <- "https://raw.githubusercontent.com/christophergandrud/d3Network/sankey/JSONdata/energy.json"
Energy <- RCurl::getURL(URL, ssl.verifypeer = TRUE)

>Error in function (type, msg, asError = TRUE)  : 
  error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

RCurl::curlVersion()$ssl_version
>> [1] "OpenSSL/1.0.0o"
```

**Comment by cjyetman** [comment]
This is not the repo for `RCurl`, so if you want that error specifically to be addressed, you'll probably have to report it to the [developers of that package](https://cran.r-project.org/package=RCurl).

In order to get examples here working that use `RCurl` to get the data, you could instead use the [more modern pkg `curl`](https://cran.r-project.org/package=curl). For example...
```r
library(curl)
library(jsonlite)
library(networkD3)

URL <- "https://raw.githubusercontent.com/christophergandrud/d3Network/sankey/JSONdata/energy.json"
energy <- fromJSON(curl(URL))

EngLinks <- energy$links
EngNodes <- energy$nodes

sankeyNetwork(Links = EngLinks, Nodes = EngNodes, Source = "source",
              Target = "target", Value = "value", NodeID = "name",
              fontSize = 12, nodeWidth = 30)
```

**Comment by dmenne** [comment]
Yes, I know this is not the curl repo, and I got it to work anyway. Just a report for easy correction in your markdown example
